### ISSUE TITLE
./mvnw clean install gets stuck

### ISSUE THREAD

**Issue by juancalvof** [PacktPublishing/Building-Big-Data-Pipelines-with-Apache-Beam#15]
Hello! Congrats on the book. Looking forward to diving into it.

Running `./mvnw clean install ` the code gets stuck on test Running `com.packtpub.beam.chapter4.SportTrackerMotivationUsingOwnJoinTest`. I have run the test directly and it works. Any idea how I can solve this? Thanks.

![image](https://user-images.githubusercontent.com/20303036/151025058-2426a9ee-7f65-4499-b058-c1aec54c3a39.png)

By the way, I needed to change the version of Lombok to 1.18.20 regarding this issue: https://github.com/projectlombok/lombok/issues/2790

**Comment by vitorfranklin** [comment]
> Hello! Congrats on the book. Looking forward to diving into it.
> 
> Running `./mvnw clean install ` the code gets stuck on test Running `com.packtpub.beam.chapter4.SportTrackerMotivationUsingOwnJoinTest`. I have run the test directly and it works. Any idea how I can solve this? Thanks.
> 
> ![image](https://user-images.githubusercontent.com/20303036/151025058-2426a9ee-7f65-4499-b058-c1aec54c3a39.png)
> 
> By the way, I needed to change the version of Lombok to 1.18.20 regarding this issue: [projectlombok/lombok#2790](https://github.com/projectlombok/lombok/issues/2790)

Hi, I think that is low memory or low cpu , I had the same problem but in my case I was using minikube, I had forgotten to set the arguments --memory and --cpu on 'minikube start'

**Comment by nithikpackt** [comment]
Thank you for the solution @vitorfranklin. Closing the issue for now.
