### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by shyaml** [PacktPublishing/Building-Big-Data-Pipelines-with-Apache-Beam#16]
Hello ,
I tried the code as it is just issue mvn  clean install  and getting this.   i tried to change the spotless maven plugin to newer version but still the same error .. running win 10 with jdk 11

[ERROR] Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:2.0.1:apply (apply) on project beam-util: Execution apply of goal com.diffplug.spotless:spotless-maven-plugin:2.0.1:apply failed: java.lang.reflect.InvocationTargetException: 1:3: error: illegal '.' -> [Help 1]

**Comment by je-ik** [comment]
Hi @shyaml, can you please elaborate more on the issue? Do you have any local modifications? Do you use WSL of plain Win environment? I'm not aware of any issues of spotless and Windows, but you can try to comment out the spotless plugin [here](https://github.com/PacktPublishing/Building-Big-Data-Pipelines-with-Apache-Beam/blob/77c86f2f983ecf55ff128bb51507802f27671d81/pom.xml#L67).

**Comment by shyaml** [comment]
@je-ik 

I am using plain windows 10 pro. I commented  out  the spotless plugin  and here is part of the  mvn install 

[INFO]
[ERROR] Errors:
[ERROR]   Chapter1DemoTest.<init>:52 » InvalidPath Illegal char <:> at index 2: /C:/User...
[ERROR]   Chapter1DemoTest.<init>:52 » InvalidPath Illegal char <:> at index 2: /C:/User...
[ERROR]   Chapter1DemoTest.<init>:52 » InvalidPath Illegal char <:> at index 2: /C:/User...
[ERROR]   Chapter1DemoTest.<init>:52 » InvalidPath Illegal char <:> at index 2: /C:/User...
[ERROR]   Chapter1DemoTest.<init>:52 » InvalidPath Illegal char <:> at index 2: /C:/User...
[ERROR]   Chapter1DemoTest.<init>:52 » InvalidPath Illegal char <:> at index 2: /C:/User...
[INFO]
[ERROR] Tests run: 6, Failures: 0, Errors: 6, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Building Big Data Pipelines with Apache Beam 1.0.0:
[INFO]
[INFO] Building Big Data Pipelines with Apache Beam ....... SUCCESS [  1.401 s]
[INFO] Building Big Data Pipelines with Apache Beam Utils . SUCCESS [ 49.484 s]
[INFO] Building Big Data Pipelines with Apache Beam Chapter 1 FAILURE [  2.091 s]
[INFO] Building Big Data Pipelines with Apache Beam Chapter 2 SKIPPED
[INFO] Building Big Data Pipelines with Apache Beam Chapter 3 SKIPPED
[INFO] Building Big Data Pipelines with Apache Beam Chapter 4 SKIPPED
[INFO] Building Big Data Pipelines with Apache Beam Chapter 5 SKIPPED
[INFO] Building Big Data Pipelines with Apache Beam Chapter 6 SKIPPED
[INFO] Building Big Data Pipelines with Apache Beam Chapter 7 SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  53.259 s
[INFO] Finished at: 2022-03-04T12:06:27+04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project beam-chapter1: There are test failures.
